"""
Model for affordable housing api
"""

FIELDS = ['OBJECTID', 'MAR_WARD', 'ADDRESS', 'PROJECT_NAME', 'STATUS_PUBLIC',
          'AGENCY_CALCULATED', 'REPORT_UNITS_AFFORDABLE', 'LATITUDE',
          'LONGITUDE', 'ADDRESS_ID', 'XCOORD', 'YCOORD', 'FULLADDRESS',
          'GIS_LAST_MOD_DTTM', 'Shape']

